# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 06 Apr 2011 07:47:10 +0000
*               @ALL          1
*               @user         8
