<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: stian
 * Date: Wed, 28 Sep 2011 00:36:37 -0400
 */

$conf['title'] = "Raw research notes and article annotations";
$conf['template'] = 'vector';
$conf['dmode'] = 0777;
$conf['fmode'] = 0666;
$conf['breadcrumbs'] = 0;
$conf['dformat'] = '%d/%m/%Y %H:%M';
$conf['tocminheads'] = '5';
$conf['useheading'] = 'navigation';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['relnofollow'] = 0;
$conf['indexdelay'] = 0;
$conf['mailguard'] = 'none';
$conf['iexssprotect'] = 0;
$conf['htmlok'] = 1;
$conf['locktime'] = 99999*60;
$conf['cachetime'] = 0;
$conf['updatecheck'] = 0;
$conf['userewrite'] = '1';
$conf['gzip_output'] = 1;
$conf['send404'] = 1;
$conf['sitemap'] = -9999999;
$conf['plugin']['aceeditor']['wraplimit'] = '160';
$conf['plugin']['disqus']['devel'] = 1;
$conf['plugin']['disqus']['shortname'] = '';
$conf['plugin']['googleanalytics']['GAID'] = '';
$conf['plugin']['googleanalytics']['dont_count_admin'] = 1;
$conf['plugin']['googleanalytics']['dont_count_users'] = 1;
$conf['plugin']['include']['showfooter'] = 0;
$conf['plugin']['include']['showdate'] = 0;
$conf['plugin']['include']['showuser'] = 0;
$conf['plugin']['include']['showcomments'] = 0;
$conf['plugin']['include']['showlinkbacks'] = 0;
$conf['plugin']['include']['showtags'] = 0;
$conf['plugin']['include']['showeditbtn'] = 0;
$conf['plugin']['include']['doredirect'] = 0;
$conf['plugin']['include']['doindent'] = 0;
$conf['plugin']['pagelist']['showheader'] = 1;
$conf['plugin']['discussion']['automatic'] = 1;
$conf['plugin']['discussion']['wikisyntaxok'] = 0;
$conf['plugin']['discussion']['newestfirst'] = 1;
$conf['plugin']['tag']['toolbar_icon'] = 1;
$conf['tpl']['vector']['vector_userpage'] = 0;
$conf['tpl']['vector']['vector_sitenotice'] = 0;
$conf['tpl']['vector']['vector_donate'] = 0;
$conf['tpl']['vector']['vector_breadcrumbs_position'] = 'top';
$conf['tpl']['vector']['vector_cite_author'] = '';
$conf['tpl']['vector']['vector_loaduserjs'] = 1;

// end auto-generated content
